=== miricmilos-Ist/Provera-znanja/magacin.dtd
<!ELEMENT artikli (artikal)+>

<!ELEMENT artikal (naziv, datumIzrade, kompanijaProdavca, (email)+)>
<!ELEMENT naziv (#PCDATA)>
<!ATTLIST naziv sifra ID #REQUIRED>

<!ELEMENT datumIzrade (dan, mesec, godina)>
<!ELEMENT dan (#PCDATA)>
<!ELEMENT mesec (#PCDATA)>
<!ELEMENT godina (#PCDATA)>

<!ELEMENT kompanijaProdavca (ime, (adresa)+)>
<!ELEMENT ime (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>

<!ELEMENT email (#PCDATA)>
<!ATTLIST email tip (sluzbeni|privatni) #REQUIRED>

=== miricmilos-Ist/Provera-znanja/magacin.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE artikli SYSTEM "magacin.dtd">
<artikli>
  <artikal>

    <naziv sifra="m55">Jabuka</naziv>

    <datumIzrade>
      <dan>2</dan>
      <mesec>4</mesec>
      <godina>1939</godina>
    </datumIzrade>

    <kompanijaProdavca>
      <ime>naziv</ime>
      <adresa>Vojvode stepe 452</adresa>
      <adresa>Vracar</adresa>
    </kompanijaProdavca>

    <email tip="privatni">mail@gmail.com</email>
    <email tip="sluzbeni">mail2@gmail.com</email>
    
  </artikal>
</artikli>
